### ISSUE TITLE
Error printing powerjoin_check

### ISSUE THREAD

**Issue by karldw** [moodymudskipper/powerjoin#11]
Thanks for the excellent powerjoin package! I noticed a small issue printing `powerjoin_check` objects. This isn't an issue when actually using `check_specs`.

```r
x = powerjoin::check_specs(duplicate_keys_left="ignore")

dput(x)
#> structure(c(duplicate_keys_left = "ignore"), class = "powerjoin_check")

print(x)
#> # powerjoin check specifications
#> Error in rlang::format_error_bullets(setNames(conflicts, icons)) : 
#>   nms %in% c("i", "x", "") are not all TRUE

traceback()
#>  6: stop(simpleError(msg, call = if (p <- sys.parent(1L)) sys.call(p)))
#>  5: stopifnot(nms %in% c("i", "x", ""))
#>  4: rlang::format_error_bullets(setNames(conflicts, icons))
#>  3: writeLines(rlang::format_error_bullets(setNames(conflicts, icons)))
#>  2: print.powerjoin_check(x)
#>  1: print(x)
```

I'm printing in a basic R terminal on linux.

**Comment by moodymudskipper** [comment]
Thanks @karldw !
You're right and I could reproduce it, it's an oversight because I was using rlang's dev version during the development.
You can fix it with `remotes::install_github("r-lib/rlang")`, I'll investigate how to work around it.

**Comment by moodymudskipper** [comment]
I think 03e383077b51863a4f1a97121863401b9ffd70fa should fix it, we use the CRAN version of {cli} instead of {rlang}, it already supports the bullet points we need. 

Does it solve it for you ?

**Comment by karldw** [comment]
That works perfectly, thanks!
