### ISSUE TITLE
stricter check

### ISSUE THREAD

**Issue by luispfonseca** [moodymudskipper/powerjoin#18]
Thank you for the great work in this package and in safejoin. Safejoin has saved me many headaches.

I'm now moving some code to powerjoin to help future reproducibility. I'm converting the old functions (safe_... to power_...). It would be useful if the check argument were stricter and would not take any of the old strings as input. For example, I'd expect this to error instead of running as if no argument was passed:

``` r
library(powerjoin)
library(tidyverse)

# toy dataset built from Allison Horst's {palmerpenguins} package and 
# Hadley Wickham's {babynames}

male_penguins <- tribble(
  ~name,    ~species,     ~island, ~flipper_length_mm, ~body_mass_g,
  "Giordan",    "Gentoo",    "Biscoe",               222L,        5250L,
  "Lynden",    "Adelie", "Torgersen",               190L,        3900L,
  "Reiner",    "Adelie",     "Dream",               185L,        3650L
)

female_penguins <- tribble(
  ~name,    ~species,  ~island, ~flipper_length_mm, ~body_mass_g,
  "Alonda",    "Gentoo", "Biscoe",               211,        4500L,
  "Ola",    "Adelie",  "Dream",               190,        3600L,
  "Mishayla",    "Gentoo", "Biscoe",               215,        4750L,
)

power_inner_join(
  male_penguins[c("species", "island")],
  female_penguins[c("species", "island")]
)
#> Joining, by = c("species", "island")
#> # A tibble: 3 × 2
#>   species island
#>   <chr>   <chr> 
#> 1 Gentoo  Biscoe
#> 2 Gentoo  Biscoe
#> 3 Adelie  Dream

# no error
power_inner_join(
  male_penguins[c("species", "island")],
  female_penguins[c("species", "island")],
  check = "B"
)
#> Joining, by = c("species", "island")
#> # A tibble: 3 × 2
#>   species island
#>   <chr>   <chr> 
#> 1 Gentoo  Biscoe
#> 2 Gentoo  Biscoe
#> 3 Adelie  Dream
```

<sup>Created on 2022-01-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

My expectation would be that only arguments as specified in check_specs() are accepted, otherwise, the function throws an error.

This could help users do the conversion, as any error would be easy to notice. Otherwise, one might miss places where the argument needs to be adjusted. Is it possible/of your interest to do so?

**Comment by moodymudskipper** [comment]
This makes sense, thanks!
